---
deployment:
  tasks:
    - export DEPLOYPATH=/home/aaroncol/wells.aaroncolon.net/wp-content/themes/wells/
    - rsync -av --exclude={".git", ".github", "/node_modules", "/vendor", ".cpanel.yml", ".DS_Store", "*.lock"} . $DEPLOYPATH
