---
deployment:
  tasks:
    - export DEPLOYPATH=/home/aaroncol/wells.aaroncolon.net/wp-content/themes/wells
    - export DEPLOYPATH2=/home/aaroncol/barbara.aaroncolon.net/wp-content/themes/wells
    - rsync -av --exclude="/.git" --exclude="/.github" --exclude="/node_modules" --exclude="/vendor" --exclude=".cpanel.yml" --exclude=".DS_Store" --exclude="*.lock" . $DEPLOYPATH
    - rsync -av --exclude="/.git" --exclude="/.github" --exclude="/node_modules" --exclude="/vendor" --exclude=".cpanel.yml" --exclude=".DS_Store" --exclude="*.lock" . $DEPLOYPATH2
    - chmod 755 /home/aaroncol/wells.aaroncolon.net/wp-content/themes/wells
    - chmod 755 /home/aaroncol/barbara.aaroncolon.net/wp-content/themes/wells
