---
deployment:
  tasks:
    - export DEPLOYPATH=/home/aaroncol/wells.aaroncolon.net/wp-content/themes/wells/
    - rsync -av --exclude=".git" --exclude=".github" --exclude="/node_modules" --exclude="/vendor" --exclude=".cpanel.yml" --exclude=".DS_Store" --exclude="*.lock" . $DEPLOYPATH
